(Convex) Pareto navigator
industrial-optimization-group/desdeo-mcdm pull request #20
Opened 2021-07-13 09:34 UTC by phoopies

Got a dev version of IND-nimbus with Pareto navigator: It crashes a lot so couldn't compare this implementation against it. Should work expect the discrete case, no clue about it.

2021-07-14 11:48 UTC, gialmisi requested changes

2021-07-14 11:48 UTC, gialmisi commented on desdeo_mcdm/interactive/ParetoNavigator.py
> +    def __init__(
The docstring describing the __init__ method should be in the respective class docstring. I.e., inside the docstring starting on line 260. Check the other docstrings for this as well.

2021-07-14 11:48 UTC, gialmisi commented on desdeo_mcdm/interactive/ParetoNavigator.py
> +        pareto_optimal_solutions: np.ndarray = None,  # Initial pareto optimal solutions
The type of 'None' is unambiguous. Could the type of 'pareto_optimal_solution' be 'Optional[np.ndarray]', for example (like on line 351)?

2021-07-14 11:48 UTC, gialmisi commented on desdeo_mcdm/interactive/ParetoNavigator.py
> +            request (Union[ParetoNavigatorInitialRequest, ParetoNavigatorRequest,
On the format of docstrings: When a description of an argument spans multiple lines, the lines following the first line should be indented. Otherwise, when sphinx generates the API documentation, it will screw it up; it thinks that every new line, that is not indented, describes a new arg. Check other occurrences of this as well. Eg., line 484.

2021-07-14 11:48 UTC, gialmisi commented on desdeo_mcdm/interactive/ParetoNavigator.py
> +        # self._weights = self.calculate_weights(self._ideal, self._nadir)
Should these be commented out or not?

2021-07-27 04:19 UTC, phoopies commented
Updated

2021-08-06 13:02 UTC, merged